### ISSUE TITLE
Support ".removeAttr('checked')" on checkbox and radio fields

### ISSUE THREAD

**Issue by erikatakahara** [elo7/doc-amd#45]
When using ".removeAttr('checked')" doesn't remove checked attribute. It should call `.checked = false` in these cases.

**Comment by tisvasconcelos** [comment]
Actually I think that the solution is to create a new method called `.prop(name [,value])`, as far as I remember, attributes are optional (can be removed) and properties are mandatory, so it can't be removed, and in this case `checked` it's a property
